# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 542ed9a713ed5ea2360c995ce85841b897c8114ec37d387a7bbf3c8de645c342933784f7077c005837bcfed16beecee703e29bbccd4012efe79cb632bbd0c8b8

test:
  secret_key_base: 6ee2f84d9a262e495fbef601fb0f741daa6ae65957f70414e375f68cd86fa74ccd9f57064580fd572a9e2408c538af7ddb76c2ecaf6419cb03a51d1045d0a34a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
