# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86056de6259e170e5f832f8ca042e2988a8b1c8d68a22b6871eb0a75dc1e30873c6e6187f908cff745dd9a9ad2a60bf1602d0409ac3b18cb8325110c1e3503ee

test:
  secret_key_base: 5e0df1d2244c5472d0ce832c16bccc4b40f5d352e799b75d2d44e754af3eb1dd7fd97b05a6da58fd1333d16ef007aaedd6451b57e3b68598731ecd356b29b710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
