source 'https://rubygems.org'


gem 'rails', '4.2.4'

gem 'rails-api'

gem 'spring', group: :development


gem 'sqlite3'

gem 'activeadmin'

# Deploy with Capistrano
# gem 'capistrano', :group => :development